name: pre-commit

on:
  push:

permissions:
  contents: read

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v6

      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.4.1
        with:
          python-version: '3.12'

      - uses: tschm/cradle/actions/deptry@v0.4.1
        with:
          source-folder: notebooks
          options: '--per-rule-ignores "DEP002=clarabel|kaleido"'

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v6

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: '--verbose --all-files'
